# Sentinel 1 A+B  SAR  Product Definitions
#
# These are used to group together the individual scene datasets
# that will be indexed into the datacube.
#
# Note: currently setting nodata as 0 rather than NaN


name: s1_gamma0_scene
description: Sentinel-1 A/B SAR Gamma0
metadata_type: eo

metadata:
  format: {name: ENVI}
  instrument: {name: SAR}
  platform: {code: SENTINEL_1}
  product_type: gamma0

measurements:
- name: vh
  units: '1'
  dtype: float32
  nodata: 0

- name: vv
  units: '1'
  dtype: float32
  nodata: 0

