# Sentinel 1 A+B  SAR  Product Definitions
#
# These are used to group together the individual scene datasets
# that will be indexed into the datacube.


name: s1a_gamma0_scene
description: Sentinel-1A SAR Gamma0
metadata_type: eo

metadata:
  format: {name: ENVI}
  instrument: {name: SAR}
  platform: {code: SENTINEL_1A}
  product_type: gamma0

measurements:
- name: vh
  units: '1'
  dtype: float32
  nodata: NaN

- name: vv
  units: '1'
  dtype: float32
  nodata: NaN

---

name: s1b_gamma0_scene
description: Sentinel-1B SAR Gamma0
metadata_type: eo

metadata:
  format: {name: ENVI}
  instrument: {name: SAR}
  platform: {code: SENTINEL_1B}
  product_type: gamma0

measurements:
- name: vh
  units: '1'
  dtype: float32
  nodata: NaN

- name: vv
  units: '1'
  dtype: float32
  nodata: NaN
